/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Bar.vue')['default']
    Bubble: typeof import('./src/components/Bubble.vue')['default']
    Doughnut: typeof import('./src/components/Doughnut.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
